### ISSUE TITLE
Auto-rotation to targets broken on v1.3.9

### ISSUE THREAD

**Issue by Gawdl3y** [Varriount/fvtt-autorotate#25]
As of v1.3.9, auto-rotation for targeted tokens no longer functions. It appears to be caused by commit ff7b193c40004409f59f72779cf094bd116dd067, which is from PR #22. [This specific change](https://github.com/Varriount/fvtt-autorotate/commit/ff7b193c40004409f59f72779cf094bd116dd067#diff-d4f4607dbc35ba83840a60a425ceb1a4672b4bd72b98ad4c0f80cb0f60602a1fR213) appears to be the culprit, as `t` is undefined.

As I posted in the PR:
```
Uncaught (in promise) ReferenceError: t is not defined
[Detected 3 packages: autorotate, smarttarget, lib-wrapper]
    at rotation.js:146:32
    at Array.map (<anonymous>)
    at Object.fn (rotation.js:141:10)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at UserTargets._hook (foundry.js:28379:11)
    at UserTargets.add (foundry.js:28350:10)
    at Token5e.setTarget (foundry.js:46646:20)
    at SmartTarget.handleTargeting (smartTarget.js:6:11)
    at Token5e._tokenOnClickLeft (smartTarget.js:17:23)
    at 🎁Token.prototype._onClickLeft#0 (libWrapper-wrapper.js:187:52)
    at MouseInteractionManager.callback (foundry.js:27723:45)
    at MouseInteractionManager._handleClickLeft (foundry.js:27920:10)
    at MouseInteractionManager._handleMouseDown (foundry.js:27900:22)
    at a.emit (index.js:181:35)
    at r.dispatchEvent (interaction.min.mjs:8:12235)
    at r.processPointerDown (interaction.min.mjs:8:14214)
    at t.recursiveFindHit (interaction.min.mjs:8:4098)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.findHit (interaction.min.mjs:8:4157)
    at r.processInteractive (interaction.min.mjs:8:12841)
    at r.onPointerDown (interaction.min.mjs:8:13543)
(anonymous) @ rotation.js:146
(anonymous) @ rotation.js:141
#call @ foundry.js:724
callAll @ foundry.js:681
_hook @ foundry.js:28379
add @ foundry.js:28350
setTarget @ foundry.js:46646
handleTargeting @ smartTarget.js:6
_tokenOnClickLeft @ smartTarget.js:17
🎁Token.prototype._onClickLeft#0 @ libWrapper-wrapper.js:187
callback @ foundry.js:27723
_handleClickLeft @ foundry.js:27920
_handleMouseDown @ foundry.js:27900
a.emit @ index.js:181
r.dispatchEvent @ interaction.min.mjs:8
r.processPointerDown @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.findHit @ interaction.min.mjs:8
r.processInteractive @ interaction.min.mjs:8
r.onPointerDown @ interaction.min.mjs:8
```
![image](https://user-images.githubusercontent.com/279900/202059597-94d803ed-5e87-4fe8-bb0d-9e21225923e7.png)

**Comment by Varriount** [comment]
This *should* be fixed in the latest release. Can you confirm?

**Comment by tokamachina** [comment]
Was having the same issue, appears fixed to me in the latest release.

**Comment by Gawdl3y** [comment]
It does seem to be fixed, yep! Much appreciated.
